In [125]:
import requests
import pandas as pd

In [126]:
headers = {
    'authority': 'api.coinhall.org',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
    'accept': '*/*',
    'sec-gpc': '1',
    'origin': 'https://coinhall.org',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://coinhall.org/',
    'accept-language': 'en-US,en;q=0.9',
}

In [127]:
response = requests.get('https://api.coinhall.org/api/v1/charts/terra/pairs', headers=headers).json()

In [128]:
df = pd.DataFrame.from_dict(response, orient='index').reset_index(drop=False).rename(columns={'index': 'address'}).drop(labels=['timestamp', 'unofficial', 'startAt', 'endAt'], axis=1)

In [152]:
astro_pairs = [
    ["bLUNA-LUNA", "terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p", 17250000],
    ["LUNA-UST", "terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6", 21750000],
    ["ANC-UST", "terra1gm5p3ner9x9xpwugn9sp6gvhd0lwrtkyrecdn3", 14250000],
    ["MIR-UST", "terra1amv303y8kzxuegvurh0gug2xe9wkgj65enq2ux", 6750000],
    ["ORION-UST", "terra1z6tp0ruxvynsx5r9mmcc2wcezz9ey9pmrw5r8g", 1500000],
    ["STT-UST", "terra19pg6d7rrndg4z4t0jhcd7z9nhl3p5ygqttxjll", 3750000],
    ["VKR-UST", "terra1e59utusv5rspqsu8t37h5w887d9rdykljedxw0", 2250000],
    ["MINE-UST", "terra178jydtjvj4gw8earkgnqc80c3hrmqj4kw2welz", 3000000],
    ["PSI-UST", "terra163pkeeuwxzr0yhndf8xd2jprm9hrtk59xf7nqf", 2250000],
    ["APOLLO-UST", "terra1xj2w7w8mx6m2nueczgsxy2gnmujwejjeu2xf78", 2250000],
]

In [153]:
pd.DataFrame(astro_pairs, colums=['pair', 'address', 'astro_tokens'])

            0                                             1         2
0  bLUNA-LUNA  terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p  17250000
1    LUNA-UST  terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6  21750000
2     ANC-UST  terra1gm5p3ner9x9xpwugn9sp6gvhd0lwrtkyrecdn3  14250000
3     MIR-UST  terra1amv303y8kzxuegvurh0gug2xe9wkgj65enq2ux   6750000
4   ORION-UST  terra1z6tp0ruxvynsx5r9mmcc2wcezz9ey9pmrw5r8g   1500000
5     STT-UST  terra19pg6d7rrndg4z4t0jhcd7z9nhl3p5ygqttxjll   3750000
6     VKR-UST  terra1e59utusv5rspqsu8t37h5w887d9rdykljedxw0   2250000
7    MINE-UST  terra178jydtjvj4gw8earkgnqc80c3hrmqj4kw2welz   3000000
8     PSI-UST  terra163pkeeuwxzr0yhndf8xd2jprm9hrtk59xf7nqf   2250000
9  APOLLO-UST  terra1xj2w7w8mx6m2nueczgsxy2gnmujwejjeu2xf78   2250000

In [130]:
astro_pairs = pd.DataFrame.from_dict(astro_pairs, orient='index').reset_index().rename(columns={'index': 'pair', 0: 'address'})

In [131]:
astro_pairs

         pair                                       address
0  bLUNA-LUNA  terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p
1    LUNA-UST  terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6
2     ANC-UST  terra1gm5p3ner9x9xpwugn9sp6gvhd0lwrtkyrecdn3
3     MIR-UST  terra1amv303y8kzxuegvurh0gug2xe9wkgj65enq2ux
4   ORION-UST  terra1z6tp0ruxvynsx5r9mmcc2wcezz9ey9pmrw5r8g
5     STT-UST  terra19pg6d7rrndg4z4t0jhcd7z9nhl3p5ygqttxjll
6     VKR-UST  terra1e59utusv5rspqsu8t37h5w887d9rdykljedxw0
7    MINE-UST  terra178jydtjvj4gw8earkgnqc80c3hrmqj4kw2welz
8     PSI-UST  terra163pkeeuwxzr0yhndf8xd2jprm9hrtk59xf7nqf
9  APOLLO-UST  terra1xj2w7w8mx6m2nueczgsxy2gnmujwejjeu2xf78

In [132]:
df = df[df['address'].isin(astro_pairs['address'])]

In [133]:
df = pd.concat([df, df['asset0'].apply(pd.Series).add_prefix('asset0_'), df['asset1'].apply(pd.Series).add_prefix('asset1_')], axis=1)

In [134]:
df = df.merge(astro_pairs, on='address')

In [135]:
df

,address,asset0,asset1,dex,asset0_contractAddress,asset0_icon,asset0_verified,asset0_name,asset0_symbol,asset0_circSupply,...,asset1_circSupplyAPI,asset1_timestamp,asset1_updatedAt,asset1_poolAmount,asset1_volume24h,asset1_volume7d,asset1_protocol,asset1_totalSupply,asset1_decimals,pair
0,terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6,"{'contractAddress': 'uusd', 'icon': 'https://a...","{'contractAddress': 'uluna', 'icon': 'https://...",Terraswap,uusd,https://assets.terra.money/icon/60/UST.png,True,TerraUSD,UST,8663742372369848,...,https://fcd.terra.dev/v1/circulatingsupply/luna,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,954893048548,1067776638047,11972663203898,NaN,NaN,NaN,LUNA-UST
1,terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p,{'contractAddress': 'terra1kc87mu460fwkqte29rq...,"{'contractAddress': 'uluna', 'icon': 'https://...",Terraswap,terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp,https://whitelist.anchorprotocol.com/logo/bLUN...,True,Bonded Luna,bLUNA,65684044706373,...,https://fcd.terra.dev/v1/circulatingsupply/luna,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,2396536987022,678073800083,5011718771910,NaN,NaN,NaN,bLUNA-LUNA
2,terra1amv303y8kzxuegvurh0gug2xe9wkgj65enq2ux,"{'contractAddress': 'uusd', 'icon': 'https://a...",{'contractAddress': 'terra15gwkyepfc6xgca5t5ze...,Terraswap,uusd,https://assets.terra.money/icon/60/UST.png,True,TerraUSD,UST,8663742372369848,...,https://graph.mirror.finance/graphql,2021-09-02T14:37:40.346Z,2021-12-12T19:45:17.750Z,10068326452775,941182698156,16429187094763,Mirror,3.705750e+14,6.0,MIR-UST
3,terra1gm5p3ner9x9xpwugn9sp6gvhd0lwrtkyrecdn3,{'contractAddress': 'terra14z56l0fp2lsf86zy3ht...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76,https://whitelist.anchorprotocol.com/logo/ANC.png,True,Anchor Token,ANC,182979594471906,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,92335417271866,6257049660405,82952746930790,NaN,NaN,NaN,ANC-UST
4,terra178jydtjvj4gw8earkgnqc80c3hrmqj4kw2welz,{'contractAddress': 'terra1kcthelkax4j9x8d3ny6...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra1kcthelkax4j9x8d3ny6sdag0qmxxynl3qtcrpy,https://assets.pylon.rocks/logo/MINE.png,True,Pylon MINE Token,MINE,896352539693846,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,36014190303527,451323453066,9196774858242,NaN,NaN,NaN,MINE-UST
5,terra19pg6d7rrndg4z4t0jhcd7z9nhl3p5ygqttxjll,"{'name': 'StarTerra Token', 'symbol': 'STT', '...","{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra13xujxcrc9dqft4p9a8ls0w3j0xnzm6y2uvve8n,https://starterra.io/assets/100x100_starterra.png,True,StarTerra Token,STT,16776643878337,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,21960519508875,882305135488,8203308141500,NaN,NaN,NaN,STT-UST
6,terra163pkeeuwxzr0yhndf8xd2jprm9hrtk59xf7nqf,{'contractAddress': 'terra12897djskt9rge8dtmm8...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra12897djskt9rge8dtmm86w654g7kzckkd698608,https://terra.nexusprotocol.app/assets/psi.png,True,Nexus Governance Token,Psi,690566429923097,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,6277627982191,18825882927320,51282910632584,NaN,NaN,NaN,PSI-UST
7,terra1e59utusv5rspqsu8t37h5w887d9rdykljedxw0,{'contractAddress': 'terra1dy9kmlm4anr92e42mrk...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra1dy9kmlm4anr92e42mrkjwzyvfqwz66un00rwr5,https://app.valkyrieprotocol.com/icon_vkr.png,True,Valkyrie Token,VKR,65751466275758,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,7108470032163,240751714947,3218817156702,NaN,NaN,NaN,VKR-UST
8,terra1z6tp0ruxvynsx5r9mmcc2wcezz9ey9pmrw5r8g,{'contractAddress': 'terra1mddcdx0ujx89f38gu7z...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra1mddcdx0ujx89f38gu7zspk2r2ffdl5enyz2u03,https://orion.money/assets/ORION-LOGO-2.1-GREE...,True,Orion Money Token,ORION,3485080800000000,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,2388985577506,283138744636,5029799289219,NaN,NaN,NaN,ORION-UST
9,terra1xj2w7w8mx6m2nueczgsxy2gnmujwejjeu2xf78,{'contractAddress': 'terra100yeqvww74h4yaejj6h...,"{'contractAddress': 'uusd', 'icon': 'https://a...",Terraswap,terra100yeqvww74h4yaejj6h733thgcafdaukjtw397,https://i.ibb.co/VC517zj/apollo.png,True,Apollo DAO Token,APOLLO,5073601805413,...,https://fcd.terra.dev/v1/circulatingsupply/ust,1970-01-01T00:00:00.000Z,2021-12-12T19:45:17.750Z,3161692345506,170584021518,3495795199137,NaN,NaN,NaN,APOLLO-UST

In [121]:
df['liquidity_usd'] = df['asset1_poolAmount'] // 1_000_000 * 2

In [116]:
df_liq = df[['asset0_name', 'asset0_symbol', 'asset1_name', 'asset1_symbol', 'liquidity_usd']]

In [138]:
luna_ust = df[df['pair'] == 'LUNA-UST']

In [148]:
luna_price = (luna_ust['asset0_poolAmount'] / luna_ust['asset1_poolAmount'])[0]
luna_price

61.834917779024885

In [150]:
mir_ust = df[df["pair"] == "MIR-UST"]
mir_ust

,address,asset0,asset1,dex,asset0_contractAddress,asset0_icon,asset0_verified,asset0_name,asset0_symbol,asset0_circSupply,...,asset1_circSupplyAPI,asset1_timestamp,asset1_updatedAt,asset1_poolAmount,asset1_volume24h,asset1_volume7d,asset1_protocol,asset1_totalSupply,asset1_decimals,pair
2,terra1amv303y8kzxuegvurh0gug2xe9wkgj65enq2ux,"{'contractAddress': 'uusd', 'icon': 'https://a...",{'contractAddress': 'terra15gwkyepfc6xgca5t5ze...,Terraswap,uusd,https://assets.terra.money/icon/60/UST.png,True,TerraUSD,UST,8663742372369848,...,https://graph.mirror.finance/graphql,2021-09-02T14:37:40.346Z,2021-12-12T19:45:17.750Z,10068326452775,941182698156,16429187094763,Mirror,3.705750e+14,6.0,MIR-UST

In [151]:
mir_ust.index

Int64Index([2], dtype='int64')

In [117]:
# fix mirror liquidity
df_liq.loc[30, 'liquidity_usd'] = df.loc[30, 'asset0_poolAmount'] // 1_000_000 * 2

/home/lejimmy/projects/crypto/astroport/venv/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [118]:
# fix luna liquidity
df_liq.loc[22, 'liquidity_usd'] = df.loc[22, 'asset0_poolAmount'] // 1_000_000 * 2

/home/lejimmy/projects/crypto/astroport/venv/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [103]:
df_liq.loc[23, 'liquidity_usd'] = int(df.loc[23, 'asset1_poolAmount'] // 1_000_000 * 2 * luna_price)

/home/lejimmy/projects/crypto/astroport/venv/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [104]:
df_liq

,asset0_name,asset0_symbol,asset1_name,asset1_symbol,liquidity_usd
22,TerraUSD,UST,Luna,LUNA,116744660
23,Bonded Luna,bLUNA,Luna,LUNA,290754416
30,TerraUSD,UST,Mirror,MIR,49328024
33,Anchor Token,ANC,TerraUSD,UST,183020304
36,Pylon MINE Token,MINE,TerraUSD,UST,72104254
71,StarTerra Token,STT,TerraUSD,UST,43619102
122,Nexus Governance Token,Psi,TerraUSD,UST,12085884
133,Valkyrie Token,VKR,TerraUSD,UST,14188112
670,Apollo DAO Token,APOLLO,TerraUSD,UST,6306892